### ISSUE TITLE
Getting invalid source release: 1.7 Error

### ISSUE THREAD

**Issue by gkteck** [spring-projects/spring-social-twitter#83]
Hi,

I am getting 

Caused by: java.lang.IllegalArgumentException: **invalid source release: 1.7**
	at com.sun.tools.javac.main.RecognizedOptions$GrumpyHelper.error(RecognizedOptions.java:75)
	at com.sun.tools.javac.main.RecognizedOptions$13.process(RecognizedOptions.java:370)
	at com.sun.tools.javac.api.JavacTool.processOptions(JavacTool.java:247)
	at com.sun.tools.javac.api.JavacTool.getTask(JavacTool.java:207)

While building using ./gradlew build

**Comment by nullpointer0x00** [comment]
Check your versions 'javac -version' and './gradlew --version'

**Comment by gkteck** [comment]
javac 1.6.0_65

------------------------------------------------------------
Gradle 1.12
------------------------------------------------------------

Build time:   2014-04-29 09:24:31 UTC
Build number: none
Revision:     a831fa866d46cbee94e61a09af15f9dd95987421

Groovy:       1.8.6
Ant:          Apache Ant(TM) version 1.9.3 compiled on December 23 2013
Ivy:          2.2.0
JVM:          1.6.0_65 (Apple Inc. 20.65-b04-466.1)

**Comment by nullpointer0x00** [comment]
The reason for the error is because you are running java 1.6 and not 1.7.

In the gradle.build file you will see this:
    compileJava {
        sourceCompatibility=1.5
        targetCompatibility=1.5
    }
    compileTestJava {
        sourceCompatibility=1.7
        targetCompatibility=1.7
    }
The tests require java 1.7 to build.  I believe you can run this command and skip building the tests: './gradlew build -x compileTestJava'
